import Head from 'next/head'
import Image from 'next/image'

// import styles from '../styles/Home.module.css'

export default function Home(props) {

 
  return (
    // className={styles.container}
    <div >
      <Head>
        <title>Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
     
      </div>
    </div>
  )
}
